version: "3.5"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - net
    volumes:
      - db:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    restart: on-failure
    volumes:
      - wp:/var/www/html
    networks:
      - net
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - nginx
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html/
    networks:
      - net

volumes:
  db:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ariahi/db
  wp:
    name: WP
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ariahi/wp

networks:
  net:
    driver: bridge
