version: "3.5"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - net
    volumes:
      - db:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    restart: on-failure
    volumes:
      - wp:/var/www/html
    networks:
      - net
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - nginx
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html/
    networks:
      - net
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - net
  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    image: cadvisor
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - net
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    restart: on-failure
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
      - '20:20'
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp:/home/ariahi/ftp
    networks:
      - net
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - net
  # static_stite:
  #   build: ./requirements/bonus/static_site
  #   container_name: static_site
  #   image: static_site
  #   restart: on-failure
  #   ports:
  #     - 80:80
  #   networks:
  #     - net

volumes:
  db:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ariahi/db
  wp:
    name: WP
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ariahi/wp

networks:
  net:
    driver: bridge
