version: "3.5"
services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "me"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "me"
    volumes:
      - ./mysql:/var/lib/mysql 
networks:
  press_net:
    ipam:
      driver: default
      config:
        - subnet: "1.1.1.0/24"
